services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: TechChallengeSQL
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong!Passw0rd
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql

  webapp:
    build: .
    depends_on:
      - sqlserver
    ports:
      - "8080:80"

volumes:
  sqlvolume: